-- =============================================================================
-- Migration: Module Rapport de coupe — tables LotCoupes et LotExports (Partie 4)
-- Date: 2026-09-05
-- Technique: Script SQL manuel (méthode établie — cf. AddStockLigneTraceability.sql).
--            dotnet-ef indisponible => DDL écrit à la main.
-- Rétrocompatible: crée 2 nouvelles tables enfants de "CommandesClients"
--            (suppression en cascade). Aucune colonne/table existante modifiée.
-- Comportement: LotCoupes = quantité coupée par taille (Σ coupé ≤ ConfigTailles.Quantite,
--            dépassement seulement si ForcerDepassement=TRUE) ; LotExports = quantité
--            exportée vers l'atelier par taille (Σ exporté ≤ Σ coupé, même règle).
--            Le rapport tissu (métrage annoncé / conso réelle / stock restant) est
--            calculé à la volée par le backend — aucune donnée métier ajoutée ici.
-- =============================================================================

-- 1. Lots de coupe (saisie des remontées atelier par taille)
CREATE TABLE IF NOT EXISTS "LotCoupes" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommandeId"        integer NOT NULL,
    "Taille"            character varying(50)  NOT NULL,
    "QuantiteCoupee"    integer NOT NULL,
    "DateCoupe"         timestamp with time zone NOT NULL,
    "EffectuePar"       character varying(100) NULL,
    "ForcerDepassement" boolean NOT NULL DEFAULT FALSE,
    "Notes"             character varying(1000) NULL,
    CONSTRAINT "FK_LotCoupes_CommandesClients_CommandeId"
        FOREIGN KEY ("CommandeId") REFERENCES "CommandesClients" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_LotCoupes_CommandeId" ON "LotCoupes" ("CommandeId");

-- 2. Lots d'export (pièces sorties vers l'atelier / la livraison, par taille)
CREATE TABLE IF NOT EXISTS "LotExports" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CommandeId"        integer NOT NULL,
    "Taille"            character varying(50)  NOT NULL,
    "QuantiteExportee"  integer NOT NULL,
    "DateExport"        timestamp with time zone NOT NULL,
    "EffectuePar"       character varying(100) NULL,
    "ForcerDepassement" boolean NOT NULL DEFAULT FALSE,
    "Notes"             character varying(1000) NULL,
    CONSTRAINT "FK_LotExports_CommandesClients_CommandeId"
        FOREIGN KEY ("CommandeId") REFERENCES "CommandesClients" ("Id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "IX_LotExports_CommandeId" ON "LotExports" ("CommandeId");

-- =============================================================================
-- Vérification attendue après exécution :
-- SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'Lot%';
-- => 2 lignes : LotCoupes, LotExports
-- =============================================================================