/* Sidecar de la migration AddPlanningDates
   (convention projet : chaque migration EF = triplet .cs/.Designer.cs + sidecar .sql
    idempotent, appliqué directement en DB docker imsjetable-db-1 GestionTextileDB).
    Cohérent avec Migrations/20260921200000_AddPlanningDates.cs */

CREATE TABLE IF NOT EXISTS "PlanningDates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlanningDates" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlanningDates_Date" ON "PlanningDates" ("Date");
INSERT INTO "PlanningDates" ("Date")
SELECT DISTINCT "DateSamedi" FROM "PlanningEntries"
WHERE "DateSamedi" IS NOT NULL
ON CONFLICT ("Date") DO NOTHING;
INSERT INTO "__EFMigrationsHistory" (MigrationId, ProductVersion)
VALUES ('20260921200000_AddPlanningDates', '9.0.16')
ON CONFLICT (MigrationId) DO NOTHING;