-- =============================================================================
-- Migration: AddOrdresFabrication (module OF — Phase 1, structure + étiquetage)
-- Date: 2026-09-17
-- Technique: Triplet manuel (.cs/.Designer.cs/.sql), DDL validé contre le dump
--            autorité dotnet-ef (`dotnet ef migrations script`) et rejoué sur
--            PostgreSQL 15 jetable. Crée les tables OrdresFabrication,
--            OrdresFabricationTailles (répartition par OF) et
--            OrdresFabricationEtiquettes (étiquettes par OF) et ajoute le
--            rattachement optionnel LotCoupe.OrdreFabricationId.
-- Rétrocompatible: ajout uniquement (3 tables + 1 colonne nullable + index).
--            Aucune colonne/table existante altérée ni supprimée. Le calcul de
--            couverture (Calculer/ValiderRessources) reste scoping commande et
--            ne référence aucune de ces tables. Unicité NumeroOF composée
--            (CommandeId, NumeroOF) — deux commandes peuvent réutiliser le même
--            numéro d'OF.
-- =============================================================================

START TRANSACTION;

-- 1. Rattachement optionnel d'une coupe à un OF (historique préservé : SetNull)
ALTER TABLE "LotCoupes" ADD "OrdreFabricationId" integer;

-- 2. Ordres de fabrication (structure scoping CommandeClient)
CREATE TABLE "OrdresFabrication" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommandeId" integer NOT NULL,
    "NumeroOF" character varying(50) NOT NULL,
    "ChaineProductionId" integer,
    "DateCreation" timestamp with time zone NOT NULL,
    "DateMiseAJour" timestamp with time zone,
    "Notes" character varying(1000),
    "CreePar" character varying(100),
    "ModifiePar" character varying(100),
    CONSTRAINT "PK_OrdresFabrication" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdresFabrication_ChainesProduction_ChaineProductionId" FOREIGN KEY ("ChaineProductionId") REFERENCES "ChainesProduction" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OrdresFabrication_CommandesClients_CommandeId" FOREIGN KEY ("CommandeId") REFERENCES "CommandesClients" ("Id") ON DELETE CASCADE
);

-- 3. Répartition par taille de chaque OF (indépendante des autres OF)
CREATE TABLE "OrdresFabricationTailles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdreFabricationId" integer NOT NULL,
    "Taille" character varying(50) NOT NULL,
    "Quantite" integer NOT NULL,
    CONSTRAINT "PK_OrdresFabricationTailles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdresFabricationTailles_OrdresFabrication_OrdreFabricationId" FOREIGN KEY ("OrdreFabricationId") REFERENCES "OrdresFabrication" ("Id") ON DELETE CASCADE
);

-- 4. Étiquettes / fournitures étiquetées portant le numéro d'OF (préoccupation
--    distincte de l'envoi vers une chaîne — EnvoiFourniture)
CREATE TABLE "OrdresFabricationEtiquettes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdreFabricationId" integer NOT NULL,
    "FournitureCommandeLigneId" integer,
    "Taille" character varying(50),
    "QuantiteEtiquettes" integer NOT NULL,
    "DateImpression" timestamp with time zone NOT NULL,
    "EffectuePar" character varying(100),
    "Notes" character varying(1000),
    CONSTRAINT "PK_OrdresFabricationEtiquettes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdresFabricationEtiquettes_FournitureCommandesLignes_FournitureCommandeLigneId" FOREIGN KEY ("FournitureCommandeLigneId") REFERENCES "FournitureCommandesLignes" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OrdresFabricationEtiquettes_OrdresFabrication_OrdreFabricationId" FOREIGN KEY ("OrdreFabricationId") REFERENCES "OrdresFabrication" ("Id") ON DELETE CASCADE
);

-- 5. Index (unicité composée NumeroOF, FK tailles/étiquettes/coupes)
CREATE UNIQUE INDEX "IX_OrdresFabrication_CommandeId_NumeroOF" ON "OrdresFabrication" ("CommandeId", "NumeroOF");
CREATE INDEX "IX_OrdresFabrication_ChaineProductionId" ON "OrdresFabrication" ("ChaineProductionId");
CREATE INDEX "IX_OrdresFabricationTailles_OrdreFabricationId" ON "OrdresFabricationTailles" ("OrdreFabricationId");
CREATE INDEX "IX_OrdresFabricationEtiquettes_OrdreFabricationId" ON "OrdresFabricationEtiquettes" ("OrdreFabricationId");
CREATE INDEX "IX_OrdresFabricationEtiquettes_FournitureCommandeLigneId" ON "OrdresFabricationEtiquettes" ("FournitureCommandeLigneId");
CREATE INDEX "IX_LotCoupes_CommandeId_OrdreFabricationId" ON "LotCoupes" ("CommandeId", "OrdreFabricationId");
CREATE INDEX "IX_LotCoupes_OrdreFabricationId" ON "LotCoupes" ("OrdreFabricationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260917120340_AddOrdresFabrication', '9.0.4');

COMMIT;