using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend_Gestion_Magasin_API.Migrations
{
    /// <inheritdoc />
    public partial class FixRoleSequence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // CORRECTIONS PRÉ-PUSH — la création d'un rôle via l'API renvoyait
            // 500 (23505 PK_Role) : SeedData insère le rôle administrateur avec
            // un Id explicite (Id=1) sur une colonne IDENTITY « generated by
            // default as identity » sans resynchroniser la séquence PostgreSQL
            // « Role_Id_seq ». Le prochain IDENTITY insert recollisionnait sur 1.
            //
            // Correctif : remise au niveau de la séquence sur MAX(Id) — idempotent
            // (l'exécution se ramène au réel maximum à chaque migration) et sans
            // effet sur les rôles existants. setval placé en double quotes sur le
            // nom de la séquence identité PG « Role_Id_seq ».
            migrationBuilder.Sql(
                "SELECT setval('\"Role_Id_seq\"', (SELECT GREATEST(MAX(\"Id\"), 1) FROM \"Role\"))");

            // Repli : si un futur insert explicite d'un Id en progrès a été fait
            // (schéma « generated by default »), l'état réel est re-mesuré au
            // prochain démarrage : la migration reste inoffensive et rejouable.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remise de la séquence à la valeur minimale (is_called = false) :
            // le prochain IDENTITY insert redémarrera à 1. Ne restaure aucune
            // donnée — reversibility symbolique, la migration n'a aucun effet
            // de données.
            migrationBuilder.Sql("SELECT setval('\"Role_Id_seq\"', 1, false)");
        }
    }
}