-- =============================================================================
-- Migration: AddArticleFournisseurNumerobainModePilotage (Séquence Partie 9 ④⑤⑥)
-- Date: 2026-09-20
-- Partie G (§5.2) : catalogue Article ↔ Fournisseur (multi-sourcing)
--     - nouvelle table ArticleFournisseurs (réf fournisseur + prix habituel +
--       délai d'approvisionnement + actif), FK Restrict ×2, index unique
--       (ArticleId, FournisseurId)
-- Partie H (§5.7) : traçabilité teinture
--     - colonne NumeroBain (nullable) sur LignesAchat et LignesImportation
-- Partie J (Partie 3) : mode de pilotage atelier
--     - colonne ModePilotage (text, NOT NULL DEFAULT 'Standard') sur CommandesClients
-- Générée et validée sous EF Core 9.0.4 (`dotnet ef migrations add`).
-- =============================================================================

START TRANSACTION;

ALTER TABLE "LignesImportation" ADD "NumeroBain" character varying(50);

ALTER TABLE "LignesAchat" ADD "NumeroBain" character varying(50);

ALTER TABLE "CommandesClients" ADD "ModePilotage" text NOT NULL DEFAULT 'Standard';

CREATE TABLE "ArticleFournisseurs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ArticleId" integer NOT NULL,
    "FournisseurId" integer NOT NULL,
    "ReferenceFournisseur" character varying(100),
    "PrixHabituel" numeric(18,4) NOT NULL,
    "DelaiApprovisionnementJours" integer,
    "EstActif" boolean NOT NULL,
    CONSTRAINT "PK_ArticleFournisseurs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ArticleFournisseurs_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ArticleFournisseurs_Fournisseurs_FournisseurId" FOREIGN KEY ("FournisseurId") REFERENCES "Fournisseurs" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_ArticleFournisseurs_ArticleId_FournisseurId" ON "ArticleFournisseurs" ("ArticleId", "FournisseurId");

CREATE INDEX "IX_ArticleFournisseurs_FournisseurId" ON "ArticleFournisseurs" ("FournisseurId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260920194701_AddArticleFournisseurNumerobainModePilotage', '9.0.4');

COMMIT;