/* Sidecar de la migration AddGroupesTaches
   (convention projet : chaque migration EF = triplet .cs/.Designer.cs + sidecar .sql
    idempotent, exécutable directement en DB — appliqué sur la PG15 jetable).
   Contenu : module « Tâches » — table GroupesTaches, lignes GroupesTachesLignes
   et rattachement optionnel TachesProduction.GroupeTacheId.
   Cohérent avec Migrations/20260924231244_AddGroupesTaches.cs.
   Additif : aucune table/colonne existante modifiée, uniquement création. */

-- 1. Rattachement optionnel d'une tâche à son groupe d'origine
--    (SetNull : l'historique des tâches générées survit à la suppression du groupe).
ALTER TABLE "TachesProduction" ADD COLUMN IF NOT EXISTS "GroupeTacheId" integer NULL;

-- 2. Groupes de tâches répétitifs (modèles applicables aux commandes)
CREATE TABLE IF NOT EXISTS "GroupesTaches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(100) NOT NULL,
    "Description" character varying(1000) NULL,
    "EstActif" boolean NOT NULL,
    "DateCreation" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GroupesTaches" PRIMARY KEY ("Id")
);

-- 3. Lignes d'un groupe (gabarit d'une tâche à générer), Cascade : le gabarit appartient au groupe.
CREATE TABLE IF NOT EXISTS "GroupesTachesLignes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupeTacheId" integer NOT NULL,
    "Titre" character varying(100) NOT NULL,
    "Description" character varying(1000) NULL,
    "EquipeAssignee" character varying(100) NULL,
    "ResponsableAssigne" character varying(100) NULL,
    "Priorite" integer NOT NULL,
    "Ordre" integer NOT NULL,
    "DureeEstimeeHeures" integer NOT NULL,
    CONSTRAINT "PK_GroupesTachesLignes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupesTachesLignes_GroupesTaches_GroupeTacheId"
        FOREIGN KEY ("GroupeTacheId") REFERENCES "GroupesTaches" ("Id") ON DELETE CASCADE
);

-- 4. Index de navigation + unicité (GroupeTacheId, Ordre) pour la séquence d'application
CREATE INDEX IF NOT EXISTS "IX_TachesProduction_GroupeTacheId" ON "TachesProduction" ("GroupeTacheId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_GroupesTachesLignes_GroupeTacheId_Ordre" ON "GroupesTachesLignes" ("GroupeTacheId", "Ordre");

-- 5. FK de TachesProduction vers GroupesTaches (SET NULL)
DO $PK$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_TachesProduction_GroupesTaches_GroupeTacheId'
    ) THEN
        ALTER TABLE "TachesProduction"
            ADD CONSTRAINT "FK_TachesProduction_GroupesTaches_GroupeTacheId"
            FOREIGN KEY ("GroupeTacheId") REFERENCES "GroupesTaches" ("Id") ON DELETE SET NULL;
    END IF;
END
$PK$;