CREATE TABLE "Matelas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroMatelas" varchar(50) NOT NULL,
    "DateMatelas" timestamp with time zone NOT NULL,
    "PiecePliage" integer NOT NULL,
    "CoupeEstimee" integer NOT NULL,
    "Notes" varchar(1000) NULL,
    "EstActif" boolean NOT NULL,
    CONSTRAINT "PK_Matelas" PRIMARY KEY ("Id")
);

CREATE TABLE "ChainesProduction" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" varchar(100) NOT NULL,
    "TypeChaine" text NOT NULL,
    "EstActif" boolean NOT NULL,
    CONSTRAINT "PK_ChainesProduction" PRIMARY KEY ("Id")
);

CREATE TABLE "FournitureCommandesLignes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommandeId" integer NOT NULL,
    "ArticleId" integer NOT NULL,
    "Portee" text NOT NULL,
    "DesignationSpecifique" varchar(200) NULL,
    "QuantiteFourniture" numeric(18,4) NOT NULL,
    "Taille" varchar(50) NULL,
    "Unite" varchar(20) NULL,
    "Notes" varchar(1000) NULL,
    CONSTRAINT "PK_FournitureCommandesLignes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FournitureCommandesLignes_Articles_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Articles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FournitureCommandesLignes_CommandesClients_CommandeId" FOREIGN KEY ("CommandeId") REFERENCES "CommandesClients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EnvoisFourniture" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommandeFournitureLigneId" integer NOT NULL,
    "ChaineProductionId" integer NULL,
    "QuantiteEnvoyee" numeric(18,4) NOT NULL,
    "DateEnvoi" timestamp with time zone NOT NULL,
    "EffectuePar" varchar(100) NULL,
    "ForcerDepassement" boolean NOT NULL,
    "Notes" varchar(1000) NULL,
    CONSTRAINT "PK_EnvoisFourniture" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnvoisFourniture_ChainesProduction_ChaineProductionId" FOREIGN KEY ("ChaineProductionId") REFERENCES "ChainesProduction" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EnvoisFourniture_FournitureCommandesLignes_CommandeFournitureLigneId" FOREIGN KEY ("CommandeFournitureLigneId") REFERENCES "FournitureCommandesLignes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReceptionsFourniture" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CommandeFournitureLigneId" integer NOT NULL,
    "QuantiteRecue" numeric(18,4) NOT NULL,
    "DateReception" timestamp with time zone NOT NULL,
    "EffectuePar" varchar(100) NULL,
    "Notes" varchar(1000) NULL,
    CONSTRAINT "PK_ReceptionsFourniture" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReceptionsFourniture_FournitureCommandesLignes_CommandeFournitureLigneId" FOREIGN KEY ("CommandeFournitureLigneId") REFERENCES "FournitureCommandesLignes" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Matelas_NumeroMatelas" ON "Matelas" ("NumeroMatelas");
CREATE UNIQUE INDEX "IX_ChainesProduction_Nom" ON "ChainesProduction" ("Nom");
CREATE INDEX "IX_FournitureCommandesLignes_ArticleId" ON "FournitureCommandesLignes" ("ArticleId");
CREATE INDEX "IX_FournitureCommandesLignes_CommandeId_ArticleId_Taille" ON "FournitureCommandesLignes" ("CommandeId", "ArticleId", "Taille");
CREATE INDEX "IX_EnvoisFourniture_ChaineProductionId" ON "EnvoisFourniture" ("ChaineProductionId");
CREATE INDEX "IX_EnvoisFourniture_CommandeFournitureLigneId_ChaineProductionId" ON "EnvoisFourniture" ("CommandeFournitureLigneId", "ChaineProductionId");
CREATE INDEX "IX_ReceptionsFourniture_CommandeFournitureLigneId" ON "ReceptionsFourniture" ("CommandeFournitureLigneId");

ALTER TABLE "Articles" ADD COLUMN "ArticleParentId" integer NULL;
CREATE INDEX "IX_Articles_ParentEnfant" ON "Articles" ("ArticleParentId", "Taille");
ALTER TABLE "Articles" ADD CONSTRAINT "FK_Articles_Articles_ArticleParentId" FOREIGN KEY ("ArticleParentId") REFERENCES "Articles" ("Id") ON DELETE RESTRICT;

ALTER TABLE "LotCoupes" ADD COLUMN "MatelasId" integer NULL;
DROP INDEX "IX_LotCoupes_CommandeId";
CREATE INDEX "IX_LotCoupes_MatelasId" ON "LotCoupes" ("MatelasId");
CREATE INDEX "IX_LotCoupes_CommandeId_MatelasId" ON "LotCoupes" ("CommandeId", "MatelasId");
ALTER TABLE "LotCoupes" ADD CONSTRAINT "FK_LotCoupes_Matelas_MatelasId" FOREIGN KEY ("MatelasId") REFERENCES "Matelas" ("Id") ON DELETE SET NULL;

ALTER TABLE "LotExports" ADD COLUMN "ChaineProductionId" integer NULL;
DROP INDEX "IX_LotExports_CommandeId";
CREATE INDEX "IX_LotExports_ChaineProductionId" ON "LotExports" ("ChaineProductionId");
CREATE INDEX "IX_LotExports_CommandeId_ChaineProductionId" ON "LotExports" ("CommandeId", "ChaineProductionId");
ALTER TABLE "LotExports" ADD CONSTRAINT "FK_LotExports_ChainesProduction_ChaineProductionId" FOREIGN KEY ("ChaineProductionId") REFERENCES "ChainesProduction" ("Id") ON DELETE SET NULL;