-- =============================================================================
-- Migration: Module Facturation — tables Factures, FactureCommandesLignes,
--            colonnes PrixFacon (commandes) et permissions facturation (rôles).
-- Date: 2026-09-05
-- Technique: Script SQL manuel (méthode établie — cf. AddStockLigneTraceability.sql).
--            dotnet-ef indisponible => DDL écrit à la main.
-- Rétrocompatible: crée 2 nouvelles tables (1 ligne de facture par commande) et
--            ajoute des colonnes NULL-ables / avec défauts. Table Role non modifiée
--            en structure (colonnes booléennes NOT NULL DEFAULT FALSE ajoutées).
-- Comportement: Facture = 1..n commandes, montants TOUJOURS calculés (jamais
--            stockés à la facture) ; FactureCommandeLigne = 1 par commande facturée
--            (Modele = commande, Quantite = façon, PrixUnitaireFacon copié depuis
--            CommandeClient.PrixFacon au moment de la création).
-- =============================================================================

-- 0. Colonnes ajoutées
ALTER TABLE "CommandesClients" ADD COLUMN IF NOT EXISTS "PrixFacon" numeric NULL;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "PeutVoirFactures"  boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "PeutGererFactures" boolean NOT NULL DEFAULT FALSE;

-- 1. Factures (en-tête de facture client)
CREATE TABLE IF NOT EXISTS "Factures" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NumeroFacture"  character varying(50)  NOT NULL,
    "DateFacture"    timestamp with time zone NOT NULL,
    "ClientId"       integer NOT NULL,
    "Devise"         character varying(10)  NULL DEFAULT 'EUR',
    "ModePaiement"   character varying(50)  NULL,
    "Rib"            character varying(100) NULL,
    "Iban"           character varying(100) NULL,
    "ModeLivraison"  character varying(50)  NULL,
    "NombreColis"    integer NULL,
    "PoidsNetKg"     numeric NULL,
    "PoidsBrutKg"    numeric NULL,
    "VolumeM3"       numeric NULL,
    "Notes"          character varying(1000) NULL,
    "Statut"         text NOT NULL DEFAULT 'Brouillon',
    "DateCreation"   timestamp with time zone NOT NULL,
    "CreePar"        character varying(100) NULL,
    CONSTRAINT "FK_Factures_Clients_ClientId"
        FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Factures_NumeroFacture" ON "Factures" ("NumeroFacture");
CREATE INDEX IF NOT EXISTS "IX_Factures_ClientId" ON "Factures" ("ClientId");

-- 2. Lignes de facture (1 par commande client)
CREATE TABLE IF NOT EXISTS "FactureCommandesLignes" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FactureId"        integer NOT NULL,
    "CommandeId"       integer NOT NULL,
    "Modele"           character varying(200) NULL,
    "Quantite"         integer NOT NULL,
    "PrixUnitaireFacon" numeric(18,4) NOT NULL,
    "MontantLigne"     numeric(18,4) NOT NULL,
    CONSTRAINT "FK_FactureCommandesLignes_Factures_FactureId"
        FOREIGN KEY ("FactureId") REFERENCES "Factures" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FactureCommandesLignes_CommandesClients_CommandeId"
        FOREIGN KEY ("CommandeId") REFERENCES "CommandesClients" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_FactureCommandesLignes_FactureId" ON "FactureCommandesLignes" ("FactureId");
CREATE INDEX IF NOT EXISTS "IX_FactureCommandesLignes_CommandeId" ON "FactureCommandesLignes" ("CommandeId");

-- =============================================================================
-- Vérification attendue après exécution :
-- \d "Factures" => colonnes + index unique NumeroFacture
-- \d "FactureCommandesLignes" => 2 FK (CASCADE vers Factures, RESTRICT vers CommandesClients)
-- SELECT COUNT(*) FROM "FactureCommandesLignes"; => 0
-- =============================================================================