-- =============================================================================
-- Migration: Référentiel Devises + TauxChanges (chantier multi-devises, Phase 2)
-- Date: 2026-08-29
-- Technique: Script SQL manuel (méthode établie — cf. ReceptionPartielle.sql,
--            AddGroupeCommande.sql). dotnet-ef indisponible => DDL écrit à la main
--            et validé contre un PostgreSQL 15 jetable avant application sur Neon.
-- Rétrocompatible: crée uniquement de nouvelles tables (aucune colonne/table modifiée).
-- Charge: seed des 2 devises actives TND (référence) + EUR.
-- =============================================================================

-- 1. Table Devises (référentiel, Code = PK string)
CREATE TABLE IF NOT EXISTS "Devises" (
    "Code"      character varying(10) NOT NULL,
    "Nom"       text NOT NULL,
    "Symbole"   text NOT NULL,
    "EstActif"  boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Devises" PRIMARY KEY ("Code")
);

-- Seed : devise de référence TND + EUR (devises actives au démarrage)
INSERT INTO "Devises" ("Code", "Nom", "Symbole", "EstActif") VALUES
    ('TND', 'Dinar Tunisien', 'DT', TRUE),
    ('EUR', 'Euro', '€', TRUE)
ON CONFLICT ("Code") DO NOTHING;

-- 2. Table TauxChanges (saisie manuelle, historique)
CREATE TABLE IF NOT EXISTS "TauxChanges" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "DeviseCode"    character varying(10) NOT NULL,
    "DateEffective" timestamp with time zone NOT NULL,
    "Taux"          numeric(18,6) NOT NULL,
    CONSTRAINT "PK_TauxChanges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TauxChanges_Devises_DeviseCode"
        FOREIGN KEY ("DeviseCode") REFERENCES "Devises" ("Code") ON DELETE RESTRICT
);

-- Index (DeviseCode, DateEffective) pour retrouver le taux applicable le plus récent
CREATE INDEX IF NOT EXISTS "IX_TauxChanges_DeviseCode_DateEffective"
    ON "TauxChanges" ("DeviseCode", "DateEffective");

-- =============================================================================
-- Vérification attendue après exécution :
-- SELECT "Code","Nom","Symbole","EstActif" FROM "Devises"; -- 2 lignes: TND, EUR
-- SELECT table_name FROM information_schema.tables WHERE table_name IN ('Devises','TauxChanges');
-- =============================================================================
