-- =============================================================================
-- Migration: AddParcMachines (module Parc Machines à coudre)
-- Date: 2026-09-16
-- Technique: Triplet manuel (.cs/.Designer.cs/.sql), DDL validé contre le dump
--            autorité dotnet-ef (`dotnet ef migrations script`) et rejoué sur
--            PostgreSQL 15 jetable. Crée les tables Machines et
--            InterventionsMachines (registre inventaire + maintenance, module
--            indépendant de TacheProduction) et expose le module métier via les
--            permissions role PeutGererMachines/PeutVoirMachines.
-- Rétrocompatible: ajout uniquement (2 tables + 2 booléens role, index et FK
--            avec suppression en cascade). Aucune colonne/table existante
--            altérée ni supprimée. Champ typo "PannneConstatee" préservé tel
--            quel (cahier des charges).
-- =============================================================================

START TRANSACTION;

-- 1. Permissions du module Parc Machines
ALTER TABLE "Role" ADD "PeutGererMachines" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Role" ADD "PeutVoirMachines" boolean NOT NULL DEFAULT FALSE;

-- 2. Registre des machines (inventaire)
CREATE TABLE "Machines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodeMachine" character varying(50) NOT NULL,
    "Marque" character varying(100),
    "Modele" character varying(100),
    "NumeroSerie" character varying(100),
    "TypeMachine" text NOT NULL,
    "DateAcquisition" timestamp with time zone,
    "Emplacement" character varying(100),
    "Statut" text NOT NULL,
    "Notes" character varying(1000),
    CONSTRAINT "PK_Machines" PRIMARY KEY ("Id")
);

-- 3. Historique de maintenance des machines
CREATE TABLE "InterventionsMachines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MachineId" integer NOT NULL,
    "TypeIntervention" text NOT NULL,
    "DateIntervention" timestamp with time zone NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "PannneConstatee" character varying(1000),
    "PiecesRemplacees" character varying(500),
    "CoutIntervention" numeric(18,4),
    "DureeImmobilisationHeures" integer,
    "EffectuePar" character varying(100),
    "ProchaineDateMaintenance" timestamp with time zone,
    "Notes" character varying(1000),
    CONSTRAINT "PK_InterventionsMachines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterventionsMachines_Machines_MachineId" FOREIGN KEY ("MachineId") REFERENCES "Machines" ("Id") ON DELETE CASCADE
);

-- 4. Index (CodeMachine unique, FK interventions)
CREATE INDEX "IX_InterventionsMachines_MachineId" ON "InterventionsMachines" ("MachineId");
CREATE UNIQUE INDEX "IX_Machines_CodeMachine" ON "Machines" ("CodeMachine");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260916174457_AddParcMachines', '9.0.4');

COMMIT;