-- =============================================================================
-- Migration: Groupe de commandes — Scope multi-commandes (LOT 1.2-1.4)
-- Date: 2026-08-25
-- Technique: Script SQL manuel (méthode établie —cf. ReceptionPartielle.sql)
-- Rétrocompatible: colonnes nullable, pas de backfill nécessaire
-- =============================================================================

-- 1. Table GroupesCommandes
CREATE TABLE IF NOT EXISTS "GroupesCommandes" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "DateCreation"  timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_GroupesCommandes" PRIMARY KEY ("Id")
);

-- 2. Table GroupeCommandeCommandes (join table)
CREATE TABLE IF NOT EXISTS "GroupeCommandeCommandes" (
    "Id"              integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupeCommandeId" integer NOT NULL,
    "CommandeClientId" integer NOT NULL,
    CONSTRAINT "PK_GroupeCommandeCommandes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupeCommandeCommandes_GroupesCommandes_GroupeCommandeId"
        FOREIGN KEY ("GroupeCommandeId") REFERENCES "GroupesCommandes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GroupeCommandeCommandes_CommandesClients_CommandeClientId"
        FOREIGN KEY ("CommandeClientId") REFERENCES "CommandesClients" ("Id") ON DELETE RESTRICT
);

-- Index unique sur (GroupeCommandeId, CommandeClientId)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_GroupeCommandeCommandes_GroupeCommandeId_CommandeClientId"
    ON "GroupeCommandeCommandes" ("GroupeCommandeId", "CommandeClientId");

-- Index individuels pour les FK
CREATE INDEX IF NOT EXISTS "IX_GroupeCommandeCommandes_GroupeCommandeId"
    ON "GroupeCommandeCommandes" ("GroupeCommandeId");

CREATE INDEX IF NOT EXISTS "IX_GroupeCommandeCommandes_CommandeClientId"
    ON "GroupeCommandeCommandes" ("CommandeClientId");

-- 3. LignesAchat : ajouter GroupeCommandeId (scope optionnel)
ALTER TABLE "LignesAchat"
    ADD COLUMN IF NOT EXISTS "GroupeCommandeId" integer;

ALTER TABLE "LignesAchat"
    ADD CONSTRAINT "FK_LignesAchat_GroupesCommandes_GroupeCommandeId"
        FOREIGN KEY ("GroupeCommandeId") REFERENCES "GroupesCommandes" ("Id") ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS "IX_LignesAchat_GroupeCommandeId"
    ON "LignesAchat" ("GroupeCommandeId");

-- 4. LignesImportation : ajouter GroupeCommandeId (scope optionnel)
ALTER TABLE "LignesImportation"
    ADD COLUMN IF NOT EXISTS "GroupeCommandeId" integer;

ALTER TABLE "LignesImportation"
    ADD CONSTRAINT "FK_LignesImportation_GroupesCommandes_GroupeCommandeId"
        FOREIGN KEY ("GroupeCommandeId") REFERENCES "GroupesCommandes" ("Id") ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS "IX_LignesImportation_GroupeCommandeId"
    ON "LignesImportation" ("GroupeCommandeId");

-- 5. Stocks : ajouter GroupeCommandeId (scope optionnel)
ALTER TABLE "Stocks"
    ADD COLUMN IF NOT EXISTS "GroupeCommandeId" integer;

ALTER TABLE "Stocks"
    ADD CONSTRAINT "FK_Stocks_GroupesCommandes_GroupeCommandeId"
        FOREIGN KEY ("GroupeCommandeId") REFERENCES "GroupesCommandes" ("Id") ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS "IX_Stocks_GroupeCommandeId"
    ON "Stocks" ("GroupeCommandeId");

-- =============================================================================
-- Vérification attendue après exécution :
-- SELECT table_name FROM information_schema.tables WHERE table_name LIKE '%Groupe%';
-- -- devrait retourner GroupesCommandes, GroupeCommandeCommandes
--
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'LignesAchat' AND column_name = 'GroupeCommandeId';
-- -- devrait retourner 1 ligne
--
-- SELECT indexname FROM pg_indexes WHERE tablename = 'GroupeCommandeCommandes' AND indexname LIKE '%unique%';
-- -- devrait retourner l'index unique sur (GroupeCommandeId, CommandeClientId)
-- =============================================================================
