/* Sidecar de la migration LOT8_Production_Qualite_CycleRetouche
   (convention projet : chaque migration EF = triplet .cs/.Designer.cs + sidecar .sql
    idempotent, exécutable directement en DB — appliqué sur la PG15 jetable).
   Contenu : module Production (PermissionService + OrdreFabricationEtape, 5.3)
             + module Qualité (cycle retouche, conception v1.1 §4.2-4.4).
   Cohérent avec Migrations/20260923214825_LOT8_Production_Qualite_CycleRetouche.cs.
   Attention : FK mutuelle ControlesQualite <-> EnvoisRetouche → contrainte ajoutée
   EN FIN de script (ordre de création des tables). */

-- 1. Permissions des modules Production / Qualité (rôle administrateur activé ci-dessous)
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "PeutVoirProduction" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "PeutGererProduction" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "PeutVoirQualite" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "PeutGererQualite" boolean NOT NULL DEFAULT FALSE;

-- 2. ChaineProduction : drapeau interne/sous-traitant — défaut TRUE (Décision Sof)
ALTER TABLE "ChainesProduction" ADD COLUMN IF NOT EXISTS "EstSousTraitant" boolean NOT NULL DEFAULT TRUE;

-- 3. Table de référence des codes défauts
CREATE TABLE IF NOT EXISTS "DefautCodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(30) NOT NULL,
    "Libelle" character varying(150) NOT NULL,
    "EstActif" boolean NOT NULL,
    CONSTRAINT "PK_DefautCodes" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_DefautCodes_Code" ON "DefautCodes" ("Code");

-- 4. Gamme opératoire d'un OF (module Production, 5.3)
CREATE TABLE IF NOT EXISTS "OrdresFabricationEtapes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdreFabricationId" integer NOT NULL,
    "TypeEtape" character varying(30) NOT NULL,
    "Statut" character varying(30) NOT NULL,
    "ChaineProductionId" integer NULL,
    "PlanningEntryId" integer NULL,
    "DateDebutPrevue" timestamp with time zone NULL,
    "DateFinPrevue" timestamp with time zone NULL,
    "DateDebutReelle" timestamp with time zone NULL,
    "DateFinReelle" timestamp with time zone NULL,
    "TempsTheoriqueHeures" numeric NOT NULL DEFAULT 0,
    "TempsReelHeures" numeric NOT NULL DEFAULT 0,
    "ResponsableAssigne" character varying(100) NULL,
    "Notes" character varying(1000) NULL,
    "DateCreation" timestamp with time zone NOT NULL,
    "DateMiseAJour" timestamp with time zone NULL,
    "CreePar" character varying(100) NULL,
    CONSTRAINT "PK_OrdresFabricationEtapes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdresFabricationEtapes_ChainesProduction_ChaineProductionId"
        FOREIGN KEY ("ChaineProductionId") REFERENCES "ChainesProduction" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_OrdresFabricationEtapes_OrdresFabrication_OrdreFabricationId"
        FOREIGN KEY ("OrdreFabricationId") REFERENCES "OrdresFabrication" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrdresFabricationEtapes_PlanningEntries_PlanningEntryId"
        FOREIGN KEY ("PlanningEntryId") REFERENCES "PlanningEntries" ("Id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_OrdresFabricationEtapes_OrdreFabricationId" ON "OrdresFabricationEtapes" ("OrdreFabricationId");
CREATE INDEX IF NOT EXISTS "IX_OrdresFabricationEtapes_ChaineProductionId" ON "OrdresFabricationEtapes" ("ChaineProductionId");
CREATE INDEX IF NOT EXISTS "IX_OrdresFabricationEtapes_PlanningEntryId" ON "OrdresFabricationEtapes" ("PlanningEntryId");

-- 5. Contrôle qualité (saisie unique réception + contrôle ; immuable après validation)
CREATE TABLE IF NOT EXISTS "ControlesQualite" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrdreFabricationId" integer NULL,
    "ChaineProductionId" integer NULL,
    "TypeControle" character varying(30) NOT NULL,
    "ControleParentId" integer NULL,
    "EnvoiRetoucheId" integer NULL,
    "Taille" character varying(50) NOT NULL,
    "QuantiteControlee" integer NOT NULL,
    "QuantiteAcceptee" integer NOT NULL,
    "QuantiteRetouche" integer NOT NULL,
    "QuantiteRebut" integer NOT NULL,
    "DateControle" timestamp with time zone NOT NULL,
    "EffectuePar" character varying(100) NULL,
    "Notes" character varying(1000) NULL,
    CONSTRAINT "PK_ControlesQualite" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ControlesQualite_ChainesProduction_ChaineProductionId"
        FOREIGN KEY ("ChaineProductionId") REFERENCES "ChainesProduction" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ControlesQualite_ControlesQualite_ControleParentId"
        FOREIGN KEY ("ControleParentId") REFERENCES "ControlesQualite" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ControlesQualite_OrdresFabrication_OrdreFabricationId"
        FOREIGN KEY ("OrdreFabricationId") REFERENCES "OrdresFabrication" ("Id") ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS "IX_ControlesQualite_ChaineProductionId" ON "ControlesQualite" ("ChaineProductionId");
CREATE INDEX IF NOT EXISTS "IX_ControlesQualite_ControleParentId" ON "ControlesQualite" ("ControleParentId");
CREATE INDEX IF NOT EXISTS "IX_ControlesQualite_EnvoiRetoucheId" ON "ControlesQualite" ("EnvoiRetoucheId");
CREATE INDEX IF NOT EXISTS "IX_ControlesQualite_OrdreFabricationId_ChaineProductionId_Taille"
    ON "ControlesQualite" ("OrdreFabricationId", "ChaineProductionId", "Taille");

-- 6. Envoi de retouche (plafond strict = retouche du contrôle, aucune forçage)
CREATE TABLE IF NOT EXISTS "EnvoisRetouche" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ControleQualiteId" integer NOT NULL,
    "ChaineProductionId" integer NOT NULL,
    "QuantiteRenvoyee" integer NOT NULL,
    "DateEnvoi" timestamp with time zone NOT NULL,
    "EffectuePar" character varying(100) NULL,
    "Notes" character varying(1000) NULL,
    CONSTRAINT "PK_EnvoisRetouche" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnvoisRetouche_ChainesProduction_ChaineProductionId"
        FOREIGN KEY ("ChaineProductionId") REFERENCES "ChainesProduction" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EnvoisRetouche_ControlesQualite_ControleQualiteId"
        FOREIGN KEY ("ControleQualiteId") REFERENCES "ControlesQualite" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_EnvoisRetouche_ControleQualiteId" ON "EnvoisRetouche" ("ControleQualiteId");
CREATE INDEX IF NOT EXISTS "IX_EnvoisRetouche_ChaineProductionId" ON "EnvoisRetouche" ("ChaineProductionId");

-- 7. Lignes de défauts rattachées à un contrôle (audit trail, immuable)
CREATE TABLE IF NOT EXISTS "ControleQualiteDefautLignes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ControleQualiteId" integer NOT NULL,
    "DefautCodeId" integer NOT NULL,
    "Quantite" integer NOT NULL,
    "Notes" character varying(1000) NULL,
    CONSTRAINT "PK_ControleQualiteDefautLignes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ControleQualiteDefautLignes_ControlesQualite_ControleQualiteId"
        FOREIGN KEY ("ControleQualiteId") REFERENCES "ControlesQualite" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ControleQualiteDefautLignes_DefautCodes_DefautCodeId"
        FOREIGN KEY ("DefautCodeId") REFERENCES "DefautCodes" ("Id") ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS "IX_ControleQualiteDefautLignes_ControleQualiteId" ON "ControleQualiteDefautLignes" ("ControleQualiteId");
CREATE INDEX IF NOT EXISTS "IX_ControleQualiteDefautLignes_DefautCodeId" ON "ControleQualiteDefautLignes" ("DefautCodeId");

-- 8. FK mutuelle déférée : ControlesQualite.EnvoiRetoucheId -> EnvoisRetouche (Restrict)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ControlesQualite_EnvoisRetouche_EnvoiRetoucheId') THEN
        ALTER TABLE "ControlesQualite"
            ADD CONSTRAINT "FK_ControlesQualite_EnvoisRetouche_EnvoiRetoucheId"
            FOREIGN KEY ("EnvoiRetoucheId") REFERENCES "EnvoisRetouche" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

-- 9. Données : admin + chaînes existantes sous-traitantes + codes défauts initiaux
UPDATE "Role" SET
    "PeutVoirProduction" = true, "PeutGererProduction" = true,
    "PeutVoirQualite" = true, "PeutGererQualite" = true
WHERE "EstAdministrateur" = true;

INSERT INTO "DefautCodes" ("Code", "Libelle", "EstActif") VALUES
    ('TIRAGE', 'Tirage / couleur non conforme', true),
    ('COUTURE', 'Couture défectueuse (points sautés, fil, ourlet)', true),
    ('DIMENSION', 'Dimension hors tolérance', true),
    ('TRACE', 'Trace / tache irréversible', true),
    ('TISSU', 'Tissu défectueux (trame, trou, défaut matière)', true),
    ('MONTAGE', 'Montage / garnissage défectueux', true),
    ('ETIQUETTE', 'Étiquette manquante ou erronée', true),
    ('AUTRE', 'Autre défaut (préciser en note)', true)
ON CONFLICT ("Code") DO NOTHING;

INSERT INTO "__EFMigrationsHistory" (MigrationId, ProductVersion)
VALUES ('20260923214825_LOT8_Production_Qualite_CycleRetouche', '9.0.16')
ON CONFLICT (MigrationId) DO NOTHING;