/* Sidecar de la migration AddPlanDeCoupeEtDimensionsMatelas
   (convention projet : chaque migration EF = triplet .cs/.Designer.cs + sidecar .sql
    idempotent, exécutable directement en DB — appliqué sur la PG15 jetable).
   Contenu : L1 Coupe — dimensions facultatifs du matelas + table PlanDeCoupeLignes
   (conception v1.1 §8.1-8.2). Cohérent avec
   Migrations/20260924120000_AddPlanDeCoupeEtDimensionsMatelas.cs.
   Additif : aucune table/colonne existante modifiée, uniquement création. */

-- 1. Dimensions facultatives d'un matelas (m / cm, libre en absence de valeur)
ALTER TABLE "Matelas" ADD COLUMN IF NOT EXISTS "Longueur" numeric NULL;
ALTER TABLE "Matelas" ADD COLUMN IF NOT EXISTS "Laize" numeric NULL;

-- 2. Plan de coupe (marker) d'un matelas : une ligne par gabarit/taille.
--    Occurrences × PiecePliage = quantité théorique de la ligne.
--    Unicité (MatelasId, Taille) = Décision 5 (un gabarit par matelas).
--    PartialIndex : on ne "crée" jamais de table existante, cf. EF convention PK "PK_".
CREATE TABLE IF NOT EXISTS "PlanDeCoupeLignes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MatelasId" integer NOT NULL,
    "Taille" character varying(50) NOT NULL,
    "Occurrences" integer NOT NULL,
    "Notes" character varying(1000) NULL,
    "DateCreation" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlanDeCoupeLignes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlanDeCoupeLignes_Matelas_MatelasId"
        FOREIGN KEY ("MatelasId") REFERENCES "Matelas" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlanDeCoupeLignes_MatelasId_Taille" ON "PlanDeCoupeLignes" ("MatelasId", "Taille");