-- AddGmailHtmlCorpsPiecesJointes
-- Corps HTML des emails + métadonnées des pièces jointes.
--
-- BodyHtml reçoit le HTML ASSAINI (scripts, on*, javascript: et iframes retirés) et ses
-- src="cid:" réécrits vers le proxy IMS : les images intégrées sont donc servies à la
-- demande depuis Gmail, jamais stockées.
--
-- GmailAttachments ne contient QUE des métadonnées (nom, type MIME, taille, Content-ID) :
-- le binaire est relu via l'API Gmail au téléchargement. L'index unique
-- (GmailMessageId, GmailAttachmentId) rend la resynchronisation idempotente.

ALTER TABLE "GmailMessages" ADD COLUMN "BodyHtml" text;

CREATE TABLE "GmailAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GmailMessageId" integer NOT NULL,
    "GmailAttachmentId" character varying(255) NOT NULL,
    "FileName" character varying(255),
    "MimeType" character varying(255),
    "SizeBytes" bigint NOT NULL,
    "IsInline" boolean NOT NULL,
    "ContentId" character varying(255),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GmailAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GmailAttachments_GmailMessages_GmailMessageId" FOREIGN KEY ("GmailMessageId")
        REFERENCES "GmailMessages" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_GmailAttachments_GmailMessageId_GmailAttachmentId"
    ON "GmailAttachments" ("GmailMessageId", "GmailAttachmentId");
