/* Sidecar de la migration AddPlanningEtNotifications
   (convention projet : chaque migration EF = triplet .cs/.Designer.cs + sidecar .sql
    idempotent, appliqué directement en DB docker imsjetable-db-1 GestionTextileDB).
    Cohérent avec Migrations/20260921070443_AddPlanningEtNotifications.cs */

ALTER TABLE "Notifications" DROP CONSTRAINT IF EXISTS "FK_Notifications_Users_UtilisateurId";
CREATE TABLE IF NOT EXISTS "PlanningEntries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChaineProductionId" integer NULL,
    "DateSamedi" timestamp with time zone NOT NULL,
    "NumeroCommande" character varying(100) NOT NULL,
    "Quantite" integer NULL,
    "EstLivree" boolean NOT NULL,
    "Notes" character varying(500) NULL,
    CONSTRAINT "PK_PlanningEntries" PRIMARY KEY ("Id")
);
CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurId" text NOT NULL,
    "Message" character varying(500) NOT NULL,
    "DateNotification" timestamp with time zone NOT NULL,
    "EstLivree" boolean NOT NULL,
    "PlanningEntryId" integer NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);
CREATE INDEX IF NOT EXISTS "IX_PlanningEntries_ChaineProductionId" ON "PlanningEntries" ("ChaineProductionId");
CREATE INDEX IF NOT EXISTS "IX_Notifications_PlanningEntryId" ON "Notifications" ("PlanningEntryId");
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId" ON "Notifications" ("UtilisateurId");
INSERT INTO "__EFMigrationsHistory" (MigrationId, ProductVersion)
VALUES ('20260921070443_AddPlanningEtNotifications', '9.0.16')
ON CONFLICT (MigrationId) DO NOTHING;
